version: '3.1'

services:
  API:
    image: 'nilin'
    container_name: 'nilin-app-container'
    ports:
      - "8080:8080"
    depends_on:
      - PostgreSQL
  PostgreSQL:
    image: 'postgres:13-alpine'
    container_name: 'nilin-postgres-container'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nilin